version: '2'
services:
  nfs-driver:
    privileged: true
    image: rancher/storage-rbd:v0.8.6
    environment:
      RANCHER_DEBUG: 'true'
    network_mode: host
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.dns: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'